- type: job
  id: IAA
  name: job-name-iaa
  playTimeTracker: JobIAA
  requirements:
    - !type:RoleTimeRequirement
      role: JobQuartermaster
      time: 7200
    - !type:RoleTimeRequirement
      role: JobCaptain
      time: 7200
    - !type:RoleTimeRequirement
      role: JobHeadOfPersonnel
      time: 7200
    - !type:RoleTimeRequirement
      role: JobChiefEngineer
      time: 7200
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 7200
    - !type:RoleTimeRequirement
      role: JobResearchDirector
      time: 7200
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 7200
  startingGear: IAAGear
  icon: "JobIconIAA"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Service
  - Brig
  - Maintenance
  - Command
  - External
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: IAAGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackIAAFilled
    shoes: ClothingShoesColorBlack
    id: IAAPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetIAA
    neck: ClothingNeckLawyerbadge
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
  underweart: ClothingUnderwearToplaceBra # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesLace # Sirena-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelIAAFilled
  duffelbag: ClothingBackpackDuffelIAAFilled
  inhand:
    - BriefcaseIAAFilled
